### ISSUE TITLE
WebView2のSmartScreen

### ISSUE THREAD

**Issue by NowDeer** [otya128/TVTDataBroadcastingWV2#2]
通信の実装、ありがとうございます。ただ、調べていたら、WebView2のSmartScreenのため、選局のたびに、MSサイトにHTTPSでアクセスに行っているようです。

**Comment by otya128** [comment]
無効にしたので発生しなくなっているはずです

**Comment by NowDeer** [comment]
ありがとうございます<(_ _)>無事、無くなりました。HybridCast対応って、予定はございますでしょうか？mpeg-dashの4K動画を、TVTestで見てみたいです～(^o^)丿

**Comment by otya128** [comment]
プラグインとして実装する場合放送の映像を埋め込むのが困難などと微妙ですがもしかしたら映像との合成を省くなどして実装するかもしれません
