### ISSUE TITLE
リモコンが表示されない

### ISSUE THREAD

**Issue by JohnDoe-001** [otya128/TVTDataBroadcastingWV2#5]
7/15のアップデート以降リモコンが表示されなくなりました
git checkout 21a718733b677abf421c820566d7eb2a1405a71e
で6/29のバージョンに戻せば正常にリモコンが表示されます
Visual Studio は 2019 と 2022 でビルドしてみましたが、どちらも同じでした

**Comment by otya128** [comment]
1f88942dddfaf29792ef04aaabdfc9e63dfd8c45 でプラグイン有効時に表示されなくなってしまっていたので修正しました
